Icw/simple
JuliaAstro/Transits.jl pull request #22
Opened 2021-05-13 12:15 UTC by icweaver

This PR updates the tests for `SimpleOrbit` and adds support for negative times

2021-05-13 22:09 UTC, icweaver commented
I'm currently setting `z` to 1 if the planet is on the half of its orbit nearest to us and 0 otherwise, but from a code re-use standpoint it would be nice if we could maintain the same condition that is only 1 while in transit. I will take a look at this next

2021-05-13 23:03 UTC, icweaver commented
Huh, just tried it out in `exoplanet`, and apparently the clipping is not just on our end:
![download](https://user-images.githubusercontent.com/25312320/118197419-f0627380-b41c-11eb-8abf-41f55251fed2.png)

I was probably just getting too caught-up in trying to make everything look like our previous transit curves. Since `exoplanet` has a [test](https://github.com/exoplanet-dev/exoplanet/blob/9c84387cccf75c17d521e924aa5bde0cc29b543d/tests/orbits/simple_test.py#L53) comparing their simple orbit to a Keplerian one, I think we should be ok. I'll switch back to what we had before with the working version of `SimpleOrbit` we have now, and add in that test as well

2021-05-14 01:28 UTC, mileslucas requested changes
I'm a bit confused- besides the `mod` vs `%`/`rem` change, everything is all good, right?

The reason why you're seeing the cutoff is because that's at exactly 1/4 the period (right?). Exoplanet basically says "you can't have a duration > period/2, but we don't stop you from trying" and I think keeping consistency with them there is good enough. I only wrote the `SimpleOrbit` because I wanted to get the limb darkening curves started and didn't want to make Keplerian orbits yet :)

2021-05-14 01:28 UTC, mileslucas commented on src/orbits/simple.jl
> +    )
```suggestion
    return SimpleOrbit(orbit.period, t0, b, orbit.duration, speed, orbit.half_period, ref_time)
```
no need to change the formatting here

2021-05-14 01:28 UTC, mileslucas commented on src/orbits/simple.jl
> +    )
```suggestion
    print(io, "SimpleOrbit(P=$P, T=$T, t0=$t0, b=$b)")
```

2021-05-14 01:28 UTC, mileslucas commented on src/orbits/simple.jl
> +    )
```suggestion
	period, t0, duration, half_period, ref_time = promote(period, t0, duration, half_period, ref_time)
```

2021-05-14 01:28 UTC, mileslucas commented on src/orbits/simple.jl
> +relative_time(orbit::SimpleOrbit, t) = mod(t - orbit.ref_time, orbit.period) - orbit.half_period
good catch!

2021-05-14 01:37 UTC, icweaver commented on src/orbits/simple.jl
> +    speed = 2.0 * sqrt(1.0 - b^2.0) / duration
I always wondered about that. Thanks!

2021-05-14 01:43 UTC, icweaver commented
> I'm a bit confused- besides the `mod` vs `%`/`rem` change, everything is all good, right?
> 
> The reason why you're seeing the cutoff is because that's at exactly 1/4 the period (right?). Exoplanet basically says "you can't have a duration > period/2, but we don't stop you from trying" and I think keeping consistency with them there is good enough. I only wrote the `SimpleOrbit` because I wanted to get the limb darkening curves started and didn't want to make Keplerian orbits yet :)

Yea, I think that is reasonable! Definitely interested to compare to our `KeplerianOrbit` curves =]

2021-05-14 14:44 UTC, icweaver reviewed
It looks like our coverage dropped just a smidge. Working on that now

2021-05-14 15:23 UTC, icweaver commented
Ok, things are looking green 👍🏾

2021-05-18 05:05 UTC, mileslucas approved these changes
Thanks @icweaver

2021-05-18 05:05 UTC, merged